### ISSUE TITLE
Investigate configuring sort-imports

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/eslint-config-amo#22]
See http://eslint.org/docs/rules/sort-imports

We already arrange imports in groups we could go further and have a rule for sorting imports.

**Comment by muffinresearch** [comment]
I'm not sure if we had previously decided sorting imports was overkill? paging @tofumatt, @EnTeQuAk, @kumar303 for input.

**Comment by tofumatt** [comment]
I think sorting imports is fine... the issue was for sorting keys and props. I would prefer EVERYTHING be sorted because we almost-always do it anyway, but imports I thought we said are fine.

**Comment by EnTeQuAk** [comment]
I'm +1 on sorting imports, I just don't do it unless it's enforced because lazy dev 🤖

**Comment by kumar303** [comment]
I find alphabetically sorting long lists to be pointless since every editor has powerful search utilities and every dev knows how to use them. Manually sorting things alphabetically always feels like an annoying chore to me. IMHO 🔥 YMMV.

**Comment by tofumatt** [comment]
It makes import lists and the like much easier to scan though. I can visually scan a list, especially during a code review (or some other time when I don't have access to my editor), and see what's being used.

It's also a way to structure imports and object keys instead of having no rule about it. I think consistency in code goes a long way to making it more readable.
