### ISSUE TITLE
Add no-trailing-spaces rule

### ISSUE THREAD

**Issue by kumar303** [mozilla/eslint-config-amo#51]
https://eslint.org/docs/rules/no-trailing-spaces

Most people have their editors configured to auto-strip whitespace but if one person doesn't, the next person will auto-strip the whitespace 🤔 It also creates confusing diffs because it's not obvious what happened -- i.e. you can't see any changes.

**Comment by bobsilverberg** [comment]
We already [have this](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/style.js#L353). I believe that the reason it was ignored in the case referenced at https://github.com/mozilla/addons-frontend/pull/4462#discussion_r173293049 is because that trailing space was inside a template string. In fact, that seems to be supported by https://github.com/eslint/eslint/pull/5797.

**Comment by kumar303** [comment]
Hmm. Let's leave this open to investigate why we didn't see an error on AMO for a template string. Maybe our libs were just out of date?

**Comment by bobsilverberg** [comment]
Sorry, I guess I shouldn’t have closed this on you. I address that in my comment above, though. The no-trailing-spaces rule ignores this by design.

**Comment by kumar303** [comment]
Oh, I misunderstood your comment. Dang. I see the problem. In trying to support empty new lines within a template string, eslint also allows trailing whitespace in *non-empty* lines.

Okay, this is working as eslint intended but that's not the behavior I would expect! I suppose there's not much to do here so I'll close it.
